### ISSUE TITLE
Google Places Autocomplete Updates

### ISSUE THREAD

**Issue by joshmedeski** [Medology/behat-google-place-autocomplete#3]
There is room for improvement and enhancements for this project. There are some basic ideas that can bring this project forward.

**Updates:**
- [ ] Creating a jQuery plugin (reusable JS) for Google Places Autocomplete feature
- [ ] Create a reusable angular directive (stdcheck.com has an imporved version)
- [ ] Fully fix and test _Puerto Rico_ functionality
- [ ] Test only using the keyboard (arrow keys and return key to select address)
- [ ] Test mobile
- [ ] Test using classes for form inputs (remove ID version)

**Comment by fiyyazp** [comment]
no need for it
