### ISSUE TITLE
[20] Update Medology/FlexibleMink

### ISSUE THREAD

**Issue by manuerumx** [Medology/behat-google-place-autocomplete#42]
# Story

## Description
As a result of an attempt to [update Laravel in Stdcheck](https://github.com/Medology/stdcheck.com/issues/8679), it was discovered that several dependencies need to be updated first.
For this project is was detected is using a `Medology/FlexibleMink` dependency that although it is not used by Laravel, it requires another dependency, which when Laravel is updated, it will also be updated and the version defined in this project prevents its use, making impossible to update STDCheck due to incompatibilities in that dependency.

## Negative Impact:
Devs cannot update other projects which use this as a dependency.

## Business Value
Reduces the time invested in maintaining the project updated.

## Notes
- The issue is part of the epic to [Update stdcheck to Laravel 6](https://github.com/Medology/stdcheck.com/issues/12864)
- `Medology/FlexibleMink` dependency must be updated first before an update to this repository is attempted

## Acceptance Criteria
- [ ] Update the project to include the latest version available for the `Medology/FlexibleMink` dependency

## Announcement Message
releasenotes:  N/A

devchat: Medology/behat-google-place-autocomplete has been updated to allow other projects that require this dependency can be updated to Laravel 6

# Proposed Solution:
Wait until a new version of the package [`Medology/FlexibleMink`](https://github.com/Medology/FlexibleMink/issues/367) is available to update the dependency in the project. 

## How will the proposed solution address the negative impact(s)?
The changes allow the project to be used  in other projects that will be required to upgrade before STDCheck can use Laravel 6 

## Side Effects
Is possible some methods require changes.

## QA Needs
If It is possible, the developer must provide a way to test the changes. Since the project is a library, is possible the changes cannot be tested until STDCheck or other projects that use this package are updated.

## Subject Matter Experts
- Donald (General & noun-store)
- Johnnie (General)

**Comment by HL-fernando-valdes** [comment]
# QA Local #42
No QA needed on Local.
