### ISSUE TITLE
[99] Fix CircleCI on 1.0 branch

### ISSUE THREAD

**Issue by aserv92** [Medology/behat-google-place-autocomplete#56]
# Story

## Description
CircleCI doesn't run on the 1.0 branch

## Negative Impact:
This disallows devs to run tests on CI for this branch.

## Business Value
Tests should run for devs to prevent breaking tests on other projects.

## Notes
The CI testing process is broken for the 1.0 because it is trying to merge with master when it should be merging with Medology/1.0

## Acceptance Criteria
- [ ] CircleCI build and test works properly on the 1.0 branch.

# Proposed Solution:
Fix the CIrcle CI configuration so it merges PRs against the 1.0 branch with the 1.0 branch

## How will the proposed solution address the negative impact(s)?
This fix should unblock the CI build and test process so all future PRs can be tested properly.

## QA Needs
Nothing to test and this is a dev only library.

## Subject Matter Experts
Donald

**Comment by izazueta** [comment]
Test are broken on CI https://app.circleci.com/pipelines/github/Medology/behat-google-place-autocomplete/134/workflows/535793c5-679f-4094-8b6a-863148129ef4/jobs/268

**Comment by PayneWheat** [comment]
Scored by Amir and Ivan
